CREATE TABLE Maps (Id INTEGER PRIMARY KEY AUTOINCREMENT, TileUrl TEXT);
CREATE TABLE Activities (Id INTEGER PRIMARY KEY AUTOINCREMENT, ParentId INTEGER, MapId INTEGER, TileUrl TEXT, FOREIGN KEY(MapId) REFERENCES Maps(Id));
CREATE TABLE Actors (Id INTEGER PRIMARY KEY AUTOINCREMENT, ActivityId INTEGER, ImageUrl TEXT, PositionX INTEGER, PositionY INTEGER, FOREIGN KEY(ActivityId) REFERENCES Activities(Id));
CREATE TABLE Actions (Id INTEGER PRIMARY KEY AUTOINCREMENT, ActivityId INTEGER, ActorId INTEGER, FOREIGN KEY(ActivityId) REFERENCES Activities(Id), FOREIGN KEY(ActorId) REFERENCES Actors(Id));
CREATE TABLE ActionParameters (Id INTEGER PRIMARY KEY AUTOINCREMENT, ActionId INTEGER, Key TEXT, Value TEXT, FOREIGN KEY(ActionId) REFERENCES Actions(Id));