CREATE TABLE Maps (Id INTEGER PRIMARY KEY AUTOINCREMENT);
CREATE TABLE Activities (Id INTEGER PRIMARY KEY AUTOINCREMENT, ParentId INTEGER, MapId INTEGER, FOREIGN KEY(MapId) REFERENCES Maps(Id));
CREATE TABLE Actors (Id INTEGER PRIMARY KEY AUTOINCREMENT, MapId INTEGER, FOREIGN KEY(MapId) REFERENCES Maps(Id));
CREATE TABLE Actions (Id INTEGER PRIMARY KEY AUTOINCREMENT, ActivityId INTEGER, ActorId INTEGER, FOREIGN KEY(ActivityId) REFERENCES Activities(Id), FOREIGN KEY(ActorId) REFERENCES Actors(Id));