CREATE TABLE [Map] (
	Id INTEGER PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	TileUrl VARCHAR(2083) NOT NULL,
	[Access] VARCHAR(10) NOT NULL
);


CREATE TABLE [Plan] (
	Id INTEGER PRIMARY KEY,
	Name VARCHAR(100) NOT NULL
);

CREATE TABLE [Step] (
	Id INTEGER PRIMARY KEY,
	PlanId INTEGER NOT NULL,
	FOREIGN KEY(PlanId) REFERENCES Plan(Id)
);